version: '3.9'

services:
  consumer_1_sample_2:
    build:
      context: .
      dockerfile: Rabbit.Consumer_1/Dockerfile
    depends_on:
      - producer_sample_2
      - rabbitmq_sample_2    
    environment:
      RABBITMQ_HOST: 'rabbitmq_sample_2'
      RABBITMQ_PORT: '5673'
      RABBITMQ_QUEUE: 'Sample_2'
      RABBITMQ_USERNAME: 'root'
      RABBITMQ_PASSWORD: 'root'
  consumer_2_sample_2:
    build:
      context: .
      dockerfile: Rabbit.Consumer_2/Dockerfile
    depends_on:
      - producer_sample_2
      - rabbitmq_sample_2    
    environment:
      RABBITMQ_HOST: 'rabbitmq_sample_2'
      RABBITMQ_PORT: '5673'
      RABBITMQ_QUEUE: 'Sample_2'
      RABBITMQ_USERNAME: 'root'
      RABBITMQ_PASSWORD: 'root'
  producer_sample_2:
    build:
      context: .
      dockerfile: Rabbit.Producer/Dockerfile
    depends_on:
      - rabbitmq_sample_2
    environment:
      RABBITMQ_HOST: 'rabbitmq_sample_2'
      RABBITMQ_PORT: '5673'
      RABBITMQ_QUEUE: 'Sample_2'
      RABBITMQ_USERNAME: 'root'
      RABBITMQ_PASSWORD: 'root'
  rabbitmq_sample_2:
      image: rabbitmq:3.9.11-management
      volumes:
        - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
        - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
      environment:
        RABBITMQ_ERLANG_COOKIE: 'mycookie'
        RABBITMQ_DEFAULT_USER: 'root'
        RABBITMQ_DEFAULT_PASS: 'root'
      ports:
          - 5673:5672
          - 15673:15672
